### ISSUE TITLE
Mouse Move

### ISSUE THREAD

**Issue by Denis231279** [adamhlt/D3D11-Overlay-ImGui#2] opened 2023-10-28 14:26 UTC
Hello, I'd like to know how to make sure that when I press the insert key my mouse can move freely because on fps games I can only move my mouse by clicking on the right click because the game blocks the mouse in the middle of the screen and I'd like to know if it's possible to block that the game can control the mouse (sorry if I expressed myself badly).

**Comment by adamhlt** [comment] 2023-10-29 08:05
Hello, if you want to be sure that the game will not handle the input when you are displaying the menu, you have to the function of the game that handle inputs. You can find CS GO hook for example.

Since the issue is not related to the project I close it.

**Closed as completed** 2023-10-29 08:05 UTC
Labels: question
